export const FoodEnum = Object.freeze({
  "kaskaval": "кашкавал",
  "shunka": "шунка",
  "sirenje": "сирење",
  "maslinki": "маслинки",
  "kromid": "кромид",
  "piperki": "пиперки",
  "slanina": "сланина",
  "pecurki": "печурки",
  "dveJajcaNaOko": "две јајца на око",
  "ajvar": "ајвар",
  "domat": "домат",
  "krastavica": "краставица",
  "peceniPiperki": "печени пирерки",
  "marula": "марула",
  "jajce": "јајце",
  "rotkvica": "ротквица",
  "magdonos": "магдонос",
  "morkov": "морков",
  "cveklo": "цвекло",
  "zelka": "зелка",
  "ajsberg": "ајсберг",
  "parmesan": "пармезан",
  "pileskoMeso": "пилешко месо",
  "kubeti": "кубети",
  "dresingSos": "дресинг сос",
  "tuna": "туна",
  "rukola": "рукола",
  "sheriDomat": "шери домат",
  "pesto": "песто",
  "mocarela": "моцарела",
  "susenDomat": "сушен домат",
  "piper": "пипер",
  "prshuta": "пршута",
  "ajdamer": "ајдамер",
  "pavlaka": "павлака",
  "lepche": "лепче",
  "pileshkaSalama": "пилешка салама",
  "namazOdJajacaIMajonez": "намаз од јајца и мајонез",
  "kiseliKrastavicki": "кесели краставички",
  "pomfrit": "помфрит",
  "kechap": "кечап",
  "majonez": "мајонез",
  "pileshko": "пилешко",
  "pileshkiStek": "пилешки стек",
  "shampinjoni": "шампињони",
  "beloVino": "бело вино",
  "tikvica": "тиквица",
  "modarDomat": "модар домат",
  "oriz": "ориз",
  "shkampi": "шкампи",
  "shkolki": "школки",
  "lignji": "лигњи",
  "hopla": "хопла",
  "cetiriSirenja": "четири сирења",
  "pelat": "пелат",
  "kulen": "кулен",
  "luk": "лук",
  "gorgonzola": "горгонзола",
});